### ISSUE TITLE
Tester la diversité d'environnements d'exécution

### ISSUE THREAD

**Issue by bbaudry** [umontreal-diro/IFT3913#8]
Tester la compatibilité dans divers environnements (OS, browsers, VMs, etc.)

```
      - name: Firefox Browser Tests
        uses: cypress-io/github-action@v1
        with:
          browser: firefox

      - name: Chrome Browser Tests
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
```
exemple pour tester sur [différents navigateurs](https://blog.maximeheckel.com/posts/running-cross-browser-cypress-github-ci/)
